import {
  access as defaultAccess,
  readdir,
  readFile as defaultReadFile,
  writeFile as defaultWriteFile,
} from "node:fs/promises";
import { dirname, isAbsolute, resolve, sep } from "node:path";

import { createDeclarDiagnostic, createDeclarError } from "./diagnostics";
import type { DeclarDiagnostic, DeclarEntrypoint } from "./types";

export interface DeclarDeclarationBundleHost {
  readonly fileExists?: (path: string) => Promise<boolean>;
  readonly readDirectory?: (path: string) => Promise<readonly string[]>;
  readonly readFile: (path: string) => Promise<string>;
  readonly writeFile?: (path: string, contents: string) => Promise<void>;
}

export interface DeclarDeclarationBundleTarget {
  readonly condition: string;
  readonly exportPath: string;
  readonly path: string;
}

export interface DeclarDeclarationBundle {
  readonly contents: string;
  readonly entrypoint: string;
  readonly path: string;
}

export interface DeclarDeclarationBundleOptions {
  readonly banner?: false | string | undefined;
  readonly entrypoints: readonly DeclarEntrypoint[];
  readonly host?: DeclarDeclarationBundleHost | undefined;
  readonly packageDir: string;
  readonly stripInternal?: boolean | undefined;
  readonly write?: boolean | undefined;
}

export interface DeclarDeclarationBundleResult {
  readonly bundles: readonly DeclarDeclarationBundle[];
  readonly diagnostics: readonly DeclarDiagnostic[];
}

interface BundleState {
  readonly diagnostics: DeclarDiagnostic[];
  readonly host: Required<DeclarDeclarationBundleHost>;
  readonly packageDir: string;
  readonly stack: string[];
  readonly stripInternal: boolean;
  readonly visited: Set<string>;
}

const defaultBanner = "/* Generated by @reliverse/declar. */";

async function readFilesRecursive(directory: string): Promise<readonly string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    const entryPath = resolve(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await readFilesRecursive(entryPath)));
      continue;
    }

    if (entry.isFile()) {
      files.push(entryPath);
    }
  }

  return files;
}

function normalizePackageDir(packageDir: string): string {
  return resolve(packageDir);
}

function normalizePath(path: string): string {
  return path.split(sep).join("/");
}

function normalizeAbsolutePath(path: string): string {
  return normalizePath(resolve(path));
}

function resolvePackageTargetPath(packageDir: string, targetPath: string): string {
  return normalizeAbsolutePath(
    isAbsolute(targetPath) ? targetPath : resolve(packageDir, targetPath),
  );
}

function isInsidePackage(packageDir: string, targetPath: string): boolean {
  const resolvedTarget = resolve(packageDir, targetPath);
  return resolvedTarget === packageDir || resolvedTarget.startsWith(`${packageDir}${sep}`);
}

function isPatternTarget(targetPath: string): boolean {
  return targetPath.includes("*");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function createPackageTargetPattern(packageDir: string, targetPath: string): RegExp {
  const normalizedPattern = normalizePath(resolve(packageDir, targetPath));
  const source = escapeRegExp(normalizedPattern).replaceAll("\\*", ".*");

  return new RegExp(`^${source}$`);
}

function isLocalSpecifier(specifier: string): boolean {
  return (
    specifier === "." ||
    specifier === ".." ||
    specifier.startsWith("./") ||
    specifier.startsWith("../")
  );
}

function createDefaultHost(
  host?: DeclarDeclarationBundleHost,
): Required<DeclarDeclarationBundleHost> {
  return {
    fileExists:
      host?.fileExists ??
      (async (path) => {
        try {
          await defaultAccess(path);
          return true;
        } catch {
          return false;
        }
      }),
    readDirectory: host?.readDirectory ?? readFilesRecursive,
    readFile: host?.readFile ?? ((path) => defaultReadFile(path, "utf8")),
    writeFile: host?.writeFile ?? ((path, contents) => defaultWriteFile(path, contents)),
  };
}

function getBundleTargetKey(target: DeclarDeclarationBundleTarget): string {
  return `${target.exportPath}:${target.condition}:${target.path}`;
}

export function collectDeclarDeclarationBundleTargets(
  entrypoints: readonly DeclarEntrypoint[],
): readonly DeclarDeclarationBundleTarget[] {
  const targets = new Map<string, DeclarDeclarationBundleTarget>();

  for (const entrypoint of entrypoints) {
    for (const condition of entrypoint.typesConditions) {
      const target: DeclarDeclarationBundleTarget = {
        condition: condition.condition,
        exportPath: entrypoint.exportPath,
        path: condition.path,
      };

      targets.set(getBundleTargetKey(target), target);
    }
  }

  return [...targets.values()].sort((left, right) => {
    const leftKey = getBundleTargetKey(left);
    const rightKey = getBundleTargetKey(right);

    return leftKey.localeCompare(rightKey);
  });
}

function createOutsidePackageDiagnostic(target: DeclarDeclarationBundleTarget): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_TARGET_OUTSIDE_PACKAGE",
    `Export ${target.exportPath} declares ${target.condition} at ${target.path}, but the target resolves outside the package directory.`,
    ["package.json", "exports", target.exportPath],
  );
}

function createPatternTargetDiagnostic(target: DeclarDeclarationBundleTarget): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_PATTERN_TARGET_UNSUPPORTED",
    `Export ${target.exportPath} declares pattern target ${target.path}, but Declar could not resolve it to concrete declaration files for bundling.`,
    ["package.json", "exports", target.exportPath],
  );
}

function createMissingEntrypointDiagnostic(): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_ENTRYPOINT_MISSING",
    "Declaration bundling needs at least one entrypoint with a concrete types condition.",
    ["package.json", "exports"],
  );
}

function createReadDiagnostic(path: string): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_READ_FAILED",
    `Declar could not read declaration file ${path}.`,
    [path],
  );
}

function createWriteDiagnostic(path: string): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_WRITE_FAILED",
    `Declar could not write bundled declaration file ${path}.`,
    [path],
  );
}

function createUnresolvedLocalImportDiagnostic(
  fromFile: string,
  specifier: string,
): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_UNRESOLVED_LOCAL_IMPORT",
    `Declar could not resolve local declaration import "${specifier}" from ${fromFile}.`,
    [fromFile],
  );
}

function createCycleDiagnostic(path: string): DeclarDiagnostic {
  return createDeclarDiagnostic(
    "DECLAR_BUNDLE_CYCLE",
    `Declar skipped already active declaration file ${path} to avoid a bundle cycle.`,
    [path],
    "warning",
  );
}

function createNameCollisionDiagnostic(path: string, name: string): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_NAME_COLLISION",
    `Declaration bundling found multiple incompatible declarations named ${name} while bundling ${path}.`,
    [path, name],
  );
}

function stripSourceMapComments(contents: string): string {
  return contents.replace(/\/\/# sourceMappingURL=.*$/gm, "").trim();
}

function lineStartsDeclaration(line: string): boolean {
  return /^\s*(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(?:class|const|enum|function|interface|namespace|type|var)\b/.test(
    line,
  );
}

function lineEndsDeclaration(line: string, braceDepth: number): boolean {
  const trimmed = line.trim();

  return braceDepth <= 0 && (trimmed.endsWith(";") || trimmed.endsWith("}"));
}

function updateBraceDepth(line: string, braceDepth: number): number {
  let nextDepth = braceDepth;

  for (const character of line) {
    if (character === "{") nextDepth += 1;
    if (character === "}") nextDepth -= 1;
  }

  return nextDepth;
}

function stripInternalDeclarations(contents: string): string {
  const lines = contents.split(/\r?\n/);
  const keptLines: string[] = [];
  let index = 0;

  while (index < lines.length) {
    const line = lines[index] ?? "";

    if (!line.includes("/**")) {
      keptLines.push(line);
      index += 1;
      continue;
    }

    const commentLines = [line];
    let commentIndex = index;

    while (!commentLines.at(-1)?.includes("*/") && commentIndex + 1 < lines.length) {
      commentIndex += 1;
      commentLines.push(lines[commentIndex] ?? "");
    }

    const comment = commentLines.join("\n");

    if (!/@(?:internal|private)\b/.test(comment)) {
      keptLines.push(...commentLines);
      index = commentIndex + 1;
      continue;
    }

    const lastCommentLine = commentLines.at(-1) ?? "";
    const commentEndIndex = lastCommentLine.indexOf("*/");
    const sameLineDeclaration =
      commentEndIndex === -1 ? "" : lastCommentLine.slice(commentEndIndex + 2).trim();
    let declarationIndex = commentIndex + 1;

    while (
      !sameLineDeclaration &&
      declarationIndex < lines.length &&
      (lines[declarationIndex] ?? "").trim() === ""
    ) {
      declarationIndex += 1;
    }

    const declarationLine = sameLineDeclaration || (lines[declarationIndex] ?? "");

    if (!lineStartsDeclaration(declarationLine)) {
      index = commentIndex + 1;
      continue;
    }

    let braceDepth = 0;

    if (sameLineDeclaration) {
      braceDepth = updateBraceDepth(sameLineDeclaration, braceDepth);

      if (lineEndsDeclaration(sameLineDeclaration, braceDepth)) {
        index = commentIndex + 1;
        continue;
      }
    }

    while (declarationIndex < lines.length) {
      const currentLine = lines[declarationIndex] ?? "";
      braceDepth = updateBraceDepth(currentLine, braceDepth);
      declarationIndex += 1;

      if (lineEndsDeclaration(currentLine, braceDepth)) {
        break;
      }
    }

    index = declarationIndex;
  }

  return keptLines.join("\n");
}

function prepareDeclarationContents(contents: string, stripInternal: boolean): string {
  const contentsWithoutSourceMaps = stripSourceMapComments(contents);

  return stripInternal
    ? stripInternalDeclarations(contentsWithoutSourceMaps)
    : contentsWithoutSourceMaps;
}

function normalizeBundleContents(contents: string, banner: false | string | undefined): string {
  const normalized = contents
    .replace(/[ \t]+$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const header = banner === false ? "" : `${banner ?? defaultBanner}\n\n`;
  return `${header}${normalized}\n`;
}

function isExternalModuleLine(line: string): boolean {
  const specifier = getModuleSpecifier(line);

  return Boolean(specifier && !isLocalSpecifier(specifier));
}

function getDeclarationCollisionName(block: string): string | undefined {
  const firstDeclarationLine = block
    .split(/\r?\n/)
    .find((line) => lineStartsDeclaration(line.trim()));

  if (!firstDeclarationLine) {
    return undefined;
  }

  const match = firstDeclarationLine.match(
    /^\s*(?:export\s+)?(?:declare\s+)?(?:abstract\s+)?(?:class|const|enum|function|interface|let|namespace|type|var)\s+(\w+)\b/,
  );

  return match?.[1];
}

function normalizeDeclarationBlock(block: string): string {
  return block.replace(/\s+/g, " ").trim();
}

function splitDeclarationBlocks(contents: string): readonly string[] {
  const lines = contents.split(/\r?\n/);
  const blocks: string[] = [];
  let currentBlock: string[] = [];
  let braceDepth = 0;

  for (const line of lines) {
    if (!line.trim()) {
      if (currentBlock.length > 0) {
        currentBlock.push(line);
      }
      continue;
    }

    currentBlock.push(line);
    braceDepth = updateBraceDepth(line, braceDepth);

    if (
      lineEndsDeclaration(line, braceDepth) ||
      (!lineStartsDeclaration(line) && braceDepth <= 0)
    ) {
      blocks.push(currentBlock.join("\n").trim());
      currentBlock = [];
      braceDepth = 0;
    }
  }

  if (currentBlock.length > 0) {
    blocks.push(currentBlock.join("\n").trim());
  }

  return blocks.filter(Boolean);
}

function normalizeBundledDeclarationGraph(
  contents: string,
  diagnostics: DeclarDiagnostic[],
  path: string,
): string {
  const externalModuleLines: string[] = [];
  const externalModuleLineKeys = new Set<string>();
  const bodyLines: string[] = [];

  for (const line of contents.split(/\r?\n/)) {
    if (isExternalModuleLine(line)) {
      const key = line.trim();

      if (!externalModuleLineKeys.has(key)) {
        externalModuleLineKeys.add(key);
        externalModuleLines.push(line);
      }

      continue;
    }

    bodyLines.push(line);
  }

  const declarationBlocks = splitDeclarationBlocks(bodyLines.join("\n"));
  const emittedBlockKeys = new Set<string>();
  const collisionNames = new Map<string, string>();
  const bodyBlocks: string[] = [];

  for (const block of declarationBlocks) {
    const normalizedBlock = normalizeDeclarationBlock(block);

    if (emittedBlockKeys.has(normalizedBlock)) {
      continue;
    }

    emittedBlockKeys.add(normalizedBlock);

    const collisionName = getDeclarationCollisionName(block);

    if (collisionName) {
      const previousBlock = collisionNames.get(collisionName);

      if (previousBlock && previousBlock !== normalizedBlock) {
        diagnostics.push(createNameCollisionDiagnostic(path, collisionName));
      } else {
        collisionNames.set(collisionName, normalizedBlock);
      }
    }

    bodyBlocks.push(block);
  }

  return [...externalModuleLines, ...bodyBlocks].join("\n\n");
}

function getModuleSpecifier(line: string): string | undefined {
  const importFromMatch = line.match(
    /^\s*import(?:\s+type)?\s+.+?\s+from\s+["']([^"']+)["']\s*;?\s*$/,
  );
  if (importFromMatch?.[1]) return importFromMatch[1];

  const sideEffectImportMatch = line.match(/^\s*import\s+["']([^"']+)["']\s*;?\s*$/);
  if (sideEffectImportMatch?.[1]) return sideEffectImportMatch[1];

  const exportFromMatch = line.match(
    /^\s*export\s+(?:type\s+)?(?:\*|\*\s+as\s+\w+|\{.*\})\s+from\s+["']([^"']+)["']\s*;?\s*$/,
  );
  if (exportFromMatch?.[1]) return exportFromMatch[1];

  return undefined;
}

function replaceKnownRuntimeExtension(path: string): readonly string[] {
  const replacements: Array<[RegExp, string]> = [
    [/\.d\.ts$/, ".d.ts"],
    [/\.d\.mts$/, ".d.mts"],
    [/\.d\.cts$/, ".d.cts"],
    [/\.mjs$/, ".d.mts"],
    [/\.cjs$/, ".d.cts"],
    [/\.js$/, ".d.ts"],
    [/\.mts$/, ".d.mts"],
    [/\.cts$/, ".d.cts"],
    [/\.ts$/, ".d.ts"],
  ];

  const candidates: string[] = [];

  for (const [pattern, replacement] of replacements) {
    if (pattern.test(path)) {
      candidates.push(path.replace(pattern, replacement));
    }
  }

  return candidates;
}

function createDeclarationCandidates(fromFile: string, specifier: string): readonly string[] {
  const basePath = resolve(dirname(fromFile), specifier);
  const candidates = [
    ...replaceKnownRuntimeExtension(basePath),
    `${basePath}.d.ts`,
    `${basePath}.d.mts`,
    `${basePath}.d.cts`,
    resolve(basePath, "index.d.ts"),
    resolve(basePath, "index.d.mts"),
    resolve(basePath, "index.d.cts"),
  ];

  return [...new Set(candidates.map(normalizeAbsolutePath))];
}

async function resolveLocalDeclarationSpecifier(
  state: BundleState,
  fromFile: string,
  specifier: string,
): Promise<string | undefined> {
  for (const candidate of createDeclarationCandidates(fromFile, specifier)) {
    if (await state.host.fileExists(candidate)) {
      return candidate;
    }
  }

  return undefined;
}

async function readDeclarationFile(state: BundleState, path: string): Promise<string | undefined> {
  try {
    return await state.host.readFile(path);
  } catch {
    state.diagnostics.push(createReadDiagnostic(path));
    return undefined;
  }
}

async function expandPatternTarget(
  packageDir: string,
  host: Required<DeclarDeclarationBundleHost>,
  target: DeclarDeclarationBundleTarget,
): Promise<readonly DeclarDeclarationBundleTarget[]> {
  const matcher = createPackageTargetPattern(packageDir, target.path);

  try {
    const files = await host.readDirectory(packageDir);
    const matchedFiles = files
      .map((file) => normalizeAbsolutePath(isAbsolute(file) ? file : resolve(packageDir, file)))
      .filter((file) => matcher.test(file))
      .sort((left, right) => left.localeCompare(right));

    return matchedFiles.map((file) => ({
      condition: target.condition,
      exportPath: target.exportPath,
      path: file,
    }));
  } catch {
    return [];
  }
}

async function expandBundleTargets(
  packageDir: string,
  host: Required<DeclarDeclarationBundleHost>,
  targets: readonly DeclarDeclarationBundleTarget[],
  diagnostics: DeclarDiagnostic[],
): Promise<readonly DeclarDeclarationBundleTarget[]> {
  const concreteTargets: DeclarDeclarationBundleTarget[] = [];

  for (const target of targets) {
    if (!isPatternTarget(target.path)) {
      concreteTargets.push(target);
      continue;
    }

    const expandedTargets = await expandPatternTarget(packageDir, host, target);

    if (expandedTargets.length === 0) {
      diagnostics.push(createPatternTargetDiagnostic(target));
      continue;
    }

    concreteTargets.push(...expandedTargets);
  }

  return concreteTargets.sort((left, right) =>
    getBundleTargetKey(left).localeCompare(getBundleTargetKey(right)),
  );
}

async function bundleDeclarationFile(state: BundleState, path: string): Promise<string> {
  const normalizedPath = normalizeAbsolutePath(path);

  if (state.stack.includes(normalizedPath)) {
    state.diagnostics.push(createCycleDiagnostic(normalizedPath));
    return "";
  }

  if (state.visited.has(normalizedPath)) {
    return "";
  }

  state.visited.add(normalizedPath);
  state.stack.push(normalizedPath);

  const contents = await readDeclarationFile(state, normalizedPath);

  if (contents === undefined) {
    state.stack.pop();
    return "";
  }

  const preparedContents = prepareDeclarationContents(contents, state.stripInternal);
  const lines = preparedContents.split(/\r?\n/);
  const bundledLines: string[] = [];

  for (const line of lines) {
    const specifier = getModuleSpecifier(line);

    if (!specifier || !isLocalSpecifier(specifier)) {
      bundledLines.push(line);
      continue;
    }

    const resolvedImport = await resolveLocalDeclarationSpecifier(state, normalizedPath, specifier);

    if (!resolvedImport) {
      state.diagnostics.push(createUnresolvedLocalImportDiagnostic(normalizedPath, specifier));
      bundledLines.push(line);
      continue;
    }

    const bundledImport = await bundleDeclarationFile(state, resolvedImport);

    if (bundledImport.trim()) {
      bundledLines.push(bundledImport.trim());
    }
  }

  state.stack.pop();

  return bundledLines.join("\n");
}

export async function bundleTypeScriptDeclarations(
  options: DeclarDeclarationBundleOptions,
): Promise<DeclarDeclarationBundleResult> {
  const packageDir = normalizePackageDir(options.packageDir);
  const host = createDefaultHost(options.host);
  const targets = collectDeclarDeclarationBundleTargets(options.entrypoints);
  const diagnostics: DeclarDiagnostic[] = [];
  const bundles: DeclarDeclarationBundle[] = [];

  if (targets.length === 0) {
    return {
      bundles,
      diagnostics: [createMissingEntrypointDiagnostic()],
    };
  }

  for (const target of await expandBundleTargets(packageDir, host, targets, diagnostics)) {
    if (!isInsidePackage(packageDir, target.path)) {
      diagnostics.push(createOutsidePackageDiagnostic(target));
      continue;
    }

    const outputPath = resolvePackageTargetPath(packageDir, target.path);

    const state: BundleState = {
      diagnostics,
      host,
      packageDir,
      stack: [],
      stripInternal: options.stripInternal ?? false,
      visited: new Set(),
    };

    const rawContents = await bundleDeclarationFile(state, outputPath);
    const normalizedGraph = normalizeBundledDeclarationGraph(rawContents, diagnostics, outputPath);
    const contents = normalizeBundleContents(normalizedGraph, options.banner);

    bundles.push({
      contents,
      entrypoint: target.exportPath,
      path: outputPath,
    });

    if (options.write === false) {
      continue;
    }

    try {
      await host.writeFile(outputPath, contents);
    } catch {
      diagnostics.push(createWriteDiagnostic(outputPath));
    }
  }

  return {
    bundles,
    diagnostics,
  };
}
