import {
  access as defaultAccess,
  readFile as defaultReadFile,
  writeFile as defaultWriteFile,
} from "node:fs/promises";
import { dirname, isAbsolute, resolve, sep } from "node:path";

import { createDeclarDiagnostic, createDeclarError } from "./diagnostics";
import type { DeclarDiagnostic, DeclarEntrypoint } from "./types";

export interface DeclarDeclarationBundleHost {
  readonly fileExists?: (path: string) => Promise<boolean>;
  readonly readFile: (path: string) => Promise<string>;
  readonly writeFile?: (path: string, contents: string) => Promise<void>;
}

export interface DeclarDeclarationBundleTarget {
  readonly condition: string;
  readonly exportPath: string;
  readonly path: string;
}

export interface DeclarDeclarationBundle {
  readonly contents: string;
  readonly entrypoint: string;
  readonly path: string;
}

export interface DeclarDeclarationBundleOptions {
  readonly banner?: false | string | undefined;
  readonly entrypoints: readonly DeclarEntrypoint[];
  readonly host?: DeclarDeclarationBundleHost | undefined;
  readonly packageDir: string;
  readonly write?: boolean | undefined;
}

export interface DeclarDeclarationBundleResult {
  readonly bundles: readonly DeclarDeclarationBundle[];
  readonly diagnostics: readonly DeclarDiagnostic[];
}

interface BundleState {
  readonly diagnostics: DeclarDiagnostic[];
  readonly host: Required<DeclarDeclarationBundleHost>;
  readonly packageDir: string;
  readonly stack: string[];
  readonly visited: Set<string>;
}

const defaultBanner = "/* Generated by @reliverse/declar. */";

function normalizePackageDir(packageDir: string): string {
  return resolve(packageDir);
}

function normalizePath(path: string): string {
  return path.split(sep).join("/");
}

function normalizeAbsolutePath(path: string): string {
  return normalizePath(resolve(path));
}

function isInsidePackage(packageDir: string, targetPath: string): boolean {
  const resolvedTarget = resolve(packageDir, targetPath);
  return resolvedTarget === packageDir || resolvedTarget.startsWith(`${packageDir}${sep}`);
}

function isPatternTarget(targetPath: string): boolean {
  return targetPath.includes("*");
}

function isLocalSpecifier(specifier: string): boolean {
  return (
    specifier === "." ||
    specifier === ".." ||
    specifier.startsWith("./") ||
    specifier.startsWith("../")
  );
}

function createDefaultHost(
  host?: DeclarDeclarationBundleHost,
): Required<DeclarDeclarationBundleHost> {
  return {
    fileExists:
      host?.fileExists ??
      (async (path) => {
        try {
          await defaultAccess(path);
          return true;
        } catch {
          return false;
        }
      }),
    readFile: host?.readFile ?? ((path) => defaultReadFile(path, "utf8")),
    writeFile: host?.writeFile ?? ((path, contents) => defaultWriteFile(path, contents)),
  };
}

function getBundleTargetKey(target: DeclarDeclarationBundleTarget): string {
  return `${target.exportPath}:${target.condition}:${target.path}`;
}

export function collectDeclarDeclarationBundleTargets(
  entrypoints: readonly DeclarEntrypoint[],
): readonly DeclarDeclarationBundleTarget[] {
  const targets = new Map<string, DeclarDeclarationBundleTarget>();

  for (const entrypoint of entrypoints) {
    for (const condition of entrypoint.typesConditions) {
      const target: DeclarDeclarationBundleTarget = {
        condition: condition.condition,
        exportPath: entrypoint.exportPath,
        path: condition.path,
      };

      targets.set(getBundleTargetKey(target), target);
    }
  }

  return [...targets.values()];
}

function createOutsidePackageDiagnostic(target: DeclarDeclarationBundleTarget): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_TARGET_OUTSIDE_PACKAGE",
    `Export ${target.exportPath} declares ${target.condition} at ${target.path}, but the target resolves outside the package directory.`,
    ["package.json", "exports", target.exportPath],
  );
}

function createPatternTargetDiagnostic(target: DeclarDeclarationBundleTarget): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_PATTERN_TARGET_UNSUPPORTED",
    `Export ${target.exportPath} declares pattern target ${target.path}, but declaration bundling needs a concrete declaration file target.`,
    ["package.json", "exports", target.exportPath],
  );
}

function createMissingEntrypointDiagnostic(): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_ENTRYPOINT_MISSING",
    "Declaration bundling needs at least one entrypoint with a concrete types condition.",
    ["package.json", "exports"],
  );
}

function createReadDiagnostic(path: string): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_READ_FAILED",
    `Declar could not read declaration file ${path}.`,
    [path],
  );
}

function createWriteDiagnostic(path: string): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_WRITE_FAILED",
    `Declar could not write bundled declaration file ${path}.`,
    [path],
  );
}

function createUnresolvedLocalImportDiagnostic(
  fromFile: string,
  specifier: string,
): DeclarDiagnostic {
  return createDeclarError(
    "DECLAR_BUNDLE_UNRESOLVED_LOCAL_IMPORT",
    `Declar could not resolve local declaration import "${specifier}" from ${fromFile}.`,
    [fromFile],
  );
}

function createCycleDiagnostic(path: string): DeclarDiagnostic {
  return createDeclarDiagnostic(
    "DECLAR_BUNDLE_CYCLE",
    `Declar skipped already active declaration file ${path} to avoid a bundle cycle.`,
    [path],
    "warning",
  );
}

function stripSourceMapComments(contents: string): string {
  return contents.replace(/\/\/# sourceMappingURL=.*$/gm, "").trim();
}

function normalizeBundleContents(contents: string, banner: false | string | undefined): string {
  const normalized = contents
    .replace(/[ \t]+$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const header = banner === false ? "" : `${banner ?? defaultBanner}\n\n`;
  return `${header}${normalized}\n`;
}

function getModuleSpecifier(line: string): string | undefined {
  const importFromMatch = line.match(
    /^\s*import(?:\s+type)?\s+.+?\s+from\s+["']([^"']+)["']\s*;?\s*$/,
  );
  if (importFromMatch?.[1]) return importFromMatch[1];

  const sideEffectImportMatch = line.match(/^\s*import\s+["']([^"']+)["']\s*;?\s*$/);
  if (sideEffectImportMatch?.[1]) return sideEffectImportMatch[1];

  const exportFromMatch = line.match(
    /^\s*export\s+(?:type\s+)?(?:\*|\{.*\})\s+from\s+["']([^"']+)["']\s*;?\s*$/,
  );
  if (exportFromMatch?.[1]) return exportFromMatch[1];

  return undefined;
}

function replaceKnownRuntimeExtension(path: string): readonly string[] {
  const replacements: Array<[RegExp, string]> = [
    [/\.d\.ts$/, ".d.ts"],
    [/\.d\.mts$/, ".d.mts"],
    [/\.d\.cts$/, ".d.cts"],
    [/\.mjs$/, ".d.mts"],
    [/\.cjs$/, ".d.cts"],
    [/\.js$/, ".d.ts"],
    [/\.mts$/, ".d.mts"],
    [/\.cts$/, ".d.cts"],
    [/\.ts$/, ".d.ts"],
  ];

  const candidates: string[] = [];

  for (const [pattern, replacement] of replacements) {
    if (pattern.test(path)) {
      candidates.push(path.replace(pattern, replacement));
    }
  }

  return candidates;
}

function createDeclarationCandidates(fromFile: string, specifier: string): readonly string[] {
  const basePath = resolve(dirname(fromFile), specifier);
  const candidates = [
    ...replaceKnownRuntimeExtension(basePath),
    `${basePath}.d.ts`,
    `${basePath}.d.mts`,
    `${basePath}.d.cts`,
    resolve(basePath, "index.d.ts"),
    resolve(basePath, "index.d.mts"),
    resolve(basePath, "index.d.cts"),
  ];

  return [...new Set(candidates.map(normalizeAbsolutePath))];
}

async function resolveLocalDeclarationSpecifier(
  state: BundleState,
  fromFile: string,
  specifier: string,
): Promise<string | undefined> {
  for (const candidate of createDeclarationCandidates(fromFile, specifier)) {
    if (await state.host.fileExists(candidate)) {
      return candidate;
    }
  }

  return undefined;
}

async function readDeclarationFile(state: BundleState, path: string): Promise<string | undefined> {
  try {
    return await state.host.readFile(path);
  } catch {
    state.diagnostics.push(createReadDiagnostic(path));
    return undefined;
  }
}

async function bundleDeclarationFile(state: BundleState, path: string): Promise<string> {
  const normalizedPath = normalizeAbsolutePath(path);

  if (state.stack.includes(normalizedPath)) {
    state.diagnostics.push(createCycleDiagnostic(normalizedPath));
    return "";
  }

  if (state.visited.has(normalizedPath)) {
    return "";
  }

  state.visited.add(normalizedPath);
  state.stack.push(normalizedPath);

  const contents = await readDeclarationFile(state, normalizedPath);

  if (contents === undefined) {
    state.stack.pop();
    return "";
  }

  const lines = stripSourceMapComments(contents).split(/\r?\n/);
  const bundledLines: string[] = [];

  for (const line of lines) {
    const specifier = getModuleSpecifier(line);

    if (!specifier || !isLocalSpecifier(specifier)) {
      bundledLines.push(line);
      continue;
    }

    const resolvedImport = await resolveLocalDeclarationSpecifier(state, normalizedPath, specifier);

    if (!resolvedImport) {
      state.diagnostics.push(createUnresolvedLocalImportDiagnostic(normalizedPath, specifier));
      bundledLines.push(line);
      continue;
    }

    const bundledImport = await bundleDeclarationFile(state, resolvedImport);

    if (bundledImport.trim()) {
      bundledLines.push(bundledImport.trim());
    }
  }

  state.stack.pop();

  return bundledLines.join("\n");
}

export async function bundleTypeScriptDeclarations(
  options: DeclarDeclarationBundleOptions,
): Promise<DeclarDeclarationBundleResult> {
  const packageDir = normalizePackageDir(options.packageDir);
  const host = createDefaultHost(options.host);
  const targets = collectDeclarDeclarationBundleTargets(options.entrypoints);
  const diagnostics: DeclarDiagnostic[] = [];
  const bundles: DeclarDeclarationBundle[] = [];

  if (targets.length === 0) {
    return {
      bundles,
      diagnostics: [createMissingEntrypointDiagnostic()],
    };
  }

  for (const target of targets) {
    if (isPatternTarget(target.path)) {
      diagnostics.push(createPatternTargetDiagnostic(target));
      continue;
    }

    if (!isInsidePackage(packageDir, target.path)) {
      diagnostics.push(createOutsidePackageDiagnostic(target));
      continue;
    }

    const outputPath = normalizeAbsolutePath(
      isAbsolute(target.path) ? target.path : resolve(packageDir, target.path),
    );

    const state: BundleState = {
      diagnostics,
      host,
      packageDir,
      stack: [],
      visited: new Set(),
    };

    const rawContents = await bundleDeclarationFile(state, outputPath);
    const contents = normalizeBundleContents(rawContents, options.banner);

    bundles.push({
      contents,
      entrypoint: target.exportPath,
      path: outputPath,
    });

    if (options.write === false) {
      continue;
    }

    try {
      await host.writeFile(outputPath, contents);
    } catch {
      diagnostics.push(createWriteDiagnostic(outputPath));
    }
  }

  return {
    bundles,
    diagnostics,
  };
}
