import { lstat, mkdir } from "node:fs/promises";
import path from "node:path";

import { PACKED_BLOCK_SEPARATOR } from "./constants";
import type {
  CliConfig,
  InputType,
  PackedBlockHeader,
  PackedInputRoot,
  PtcUnpackRunResult,
  UnpackFile,
  UnpackResult,
} from "./types";
import { isNodeError, PackedPathError } from "./utils/errors";
import { isPathInside, isSamePath, normalizePathForDisplay, resolveUserPath } from "./utils/path";
import { escapeRegExp, getUtf8ByteLength, readTextFile } from "./utils/text";

export async function runPtcUnpack(config: CliConfig): Promise<PtcUnpackRunResult> {
  const inputAbsPath = resolveUserPath(config.inputPaths[0] ?? "");
  const inputStats = await lstat(inputAbsPath).catch((error: unknown) => {
    if (isNodeError(error) && error.code === "ENOENT") {
      throw new Error(`Packed context file does not exist: ${inputAbsPath}`);
    }

    throw error;
  });

  if (!inputStats.isFile()) {
    throw new Error(`Packed context input must be a file: ${inputAbsPath}`);
  }

  const packedText = await readTextFile(inputAbsPath);
  const unpack = await createUnpackPlan({
    configuredBasePath: config.outputPath,
    inputAbsPath,
    overwrite: config.overwrite,
    packedText,
  });

  if (!config.apply) {
    return { mode: "unpack", config, unpack };
  }

  let bytesWritten = 0;

  for (const file of unpack.files) {
    if (file.skippedReason) {
      continue;
    }

    await mkdir(path.dirname(file.targetAbsPath), { recursive: true });
    await Bun.write(file.targetAbsPath, file.content);
    bytesWritten += file.contentBytes;
  }

  return { mode: "unpack", config, unpack, bytesWritten };
}

async function createUnpackPlan(options: {
  configuredBasePath: string | undefined;
  inputAbsPath: string;
  overwrite: boolean;
  packedText: string;
}): Promise<UnpackResult> {
  const packedProjectRoot = parsePackedProjectRoot(options.packedText);
  const baseAbsPath = options.configuredBasePath
    ? resolveUserPath(options.configuredBasePath)
    : path.normalize(process.cwd());
  const baseProvidedBy = options.configuredBasePath ? "output" : "cwd";

  if (!isSamePath(baseAbsPath, packedProjectRoot)) {
    throw new Error(
      [
        "Unpack base path does not match the original packed project root.",
        `Expected: ${packedProjectRoot}`,
        `Actual: ${baseAbsPath}`,
        "Fix: run the command from the original project root, or pass that exact path with -o.",
      ].join("\n"),
    );
  }

  const inputRoots = parsePackedInputRoots(options.packedText, packedProjectRoot);
  const headers = parsePackedBlockHeaders(options.packedText);

  if (headers.length === 0) {
    throw new Error("No packed file blocks found. Expected a PTC file generated by `rse ptc`.");
  }

  const inputRootsByLabel = new Map(inputRoots.map((root) => [root.label, root]));
  const files: UnpackFile[] = [];
  const warnings: string[] = [];
  const recommendations: string[] = [];
  const seenTargets = new Set<string>();

  for (let index = 0; index < headers.length; index += 1) {
    const header = headers[index];
    const nextHeader = headers[index + 1];

    if (!header) {
      continue;
    }

    files.push(
      await createUnpackFilePlan({
        baseAbsPath,
        header,
        nextHeader,
        inputRootsByLabel,
        overwrite: options.overwrite,
        packedText: options.packedText,
        seenTargets,
      }),
    );
  }

  const skippedFiles = files.filter((file) => file.skippedReason);

  if (skippedFiles.length > 0) {
    warnings.push(
      `${skippedFiles.length} file(s) will be skipped. See the skipped file list above.`,
    );
  }

  if (!options.overwrite && files.some((file) => file.exists)) {
    recommendations.push(
      "Re-run with --overwrite --apply if replacing existing target files is intentional.",
    );
  }

  return {
    inputAbsPath: options.inputAbsPath,
    packedProjectRoot,
    baseAbsPath,
    baseProvidedBy,
    inputRoots,
    files,
    warnings,
    recommendations,
  };
}

async function createUnpackFilePlan(options: {
  baseAbsPath: string;
  header: PackedBlockHeader;
  nextHeader: PackedBlockHeader | undefined;
  inputRootsByLabel: Map<string, PackedInputRoot>;
  overwrite: boolean;
  packedText: string;
  seenTargets: Set<string>;
}): Promise<UnpackFile> {
  const { baseAbsPath, header, nextHeader, inputRootsByLabel, overwrite, packedText, seenTargets } =
    options;
  const rawContent = packedText.slice(
    header.contentStart,
    nextHeader ? nextHeader.index : packedText.length,
  );
  const content = normalizeUnpackedContent(rawContent, header.sizeBytes);
  const contentBytes = getUtf8ByteLength(content);
  const inputRoot = inputRootsByLabel.get(header.inputLabel);

  let targetAbsPath = "";
  let relativeTargetPath = header.filePath;
  let exists = false;
  let skippedReason: string | null = null;

  if (contentBytes !== header.sizeBytes) {
    skippedReason = `content bytes do not match metadata: expected ${header.sizeBytes}, got ${contentBytes}`;
  }

  if (!inputRoot) {
    skippedReason = skippedReason ?? `unknown input label: ${header.inputLabel}`;
  }

  if (inputRoot) {
    try {
      const resolvedTarget = resolvePackedOutputPath(baseAbsPath, inputRoot, header.filePath);
      targetAbsPath = resolvedTarget.targetAbsPath;
      relativeTargetPath = resolvedTarget.relativeTargetPath;
    } catch (error) {
      if (error instanceof PackedPathError) {
        skippedReason = skippedReason ?? error.message;
      } else {
        throw error;
      }
    }
  }

  if (targetAbsPath) {
    if (seenTargets.has(targetAbsPath)) {
      skippedReason = skippedReason ?? "duplicate target path in packed context";
    }

    seenTargets.add(targetAbsPath);

    try {
      const targetStats = await lstat(targetAbsPath);
      exists = true;

      if (targetStats.isDirectory()) {
        skippedReason = skippedReason ?? "target path is a directory";
      } else if (targetStats.isSymbolicLink()) {
        skippedReason = skippedReason ?? "target path is a symlink";
      } else if (!targetStats.isFile()) {
        skippedReason = skippedReason ?? "target path is not a regular file";
      } else if (!overwrite) {
        skippedReason = skippedReason ?? "target file already exists";
      }
    } catch (error) {
      if (!isNodeError(error) || error.code !== "ENOENT") {
        skippedReason = skippedReason ?? "cannot inspect target path";
      }
    }
  }

  return {
    packedPath: header.filePath,
    relativeTargetPath,
    targetAbsPath,
    inputLabel: header.inputLabel,
    expectedSizeBytes: header.sizeBytes,
    contentBytes,
    content,
    exists,
    action: exists ? "overwrite" : "write",
    skippedReason,
  };
}

function parsePackedProjectRoot(packedText: string): string {
  const projectRootMatch = packedText.match(/^- Project root: (.+)$/m);

  if (projectRootMatch?.[1]) {
    return path.normalize(projectRootMatch[1].trim());
  }

  const outputFileMatch = packedText.match(/^- Output file: (.+)$/m);

  if (!outputFileMatch?.[1]) {
    throw new Error(
      "Packed context is missing `Project root` metadata, so the original project root cannot be verified.",
    );
  }

  return path.normalize(path.dirname(outputFileMatch[1].trim()));
}

function parsePackedInputRoots(packedText: string, packedProjectRoot: string): PackedInputRoot[] {
  const lines = packedText.split(/\r?\n/);
  const roots: PackedInputRoot[] = [];
  let current: (Partial<PackedInputRoot> & { index: number }) | null = null;

  const pushCurrent = () => {
    if (!current) {
      return;
    }

    if (!current.label || !current.resolvedPath) {
      current = null;
      return;
    }

    const resolvedPath = path.normalize(current.resolvedPath);
    const type = current.type ?? "directory";

    if (
      !isSamePath(resolvedPath, packedProjectRoot) &&
      !isPathInside(packedProjectRoot, resolvedPath)
    ) {
      throw new Error(
        `Packed input root is outside the original project root: ${resolvedPath}. Refusing to unpack absolute paths outside the project tree.`,
      );
    }

    roots.push({
      index: current.index,
      label: current.label,
      resolvedPath,
      type,
      relativeRoot: getPackedInputRelativeRoot(packedProjectRoot, resolvedPath, type),
    });
    current = null;
  };

  for (const line of lines) {
    const inputMatch = line.match(/^- Input (\d+): /);

    if (inputMatch) {
      pushCurrent();
      current = { index: Number(inputMatch[1]) - 1 };
      continue;
    }

    if (!current) {
      continue;
    }

    const labelMatch = line.match(/^  - Label: (.+)$/);

    if (labelMatch?.[1]) {
      current.label = labelMatch[1].trim();
      continue;
    }

    const resolvedMatch = line.match(/^  - Resolved: (.+)$/);

    if (resolvedMatch?.[1]) {
      current.resolvedPath = resolvedMatch[1].trim();
      continue;
    }

    const typeMatch = line.match(/^  - Type: (.+)$/);

    if (typeMatch?.[1]) {
      current.type = parseInputType(typeMatch[1]);
    }
  }

  pushCurrent();

  if (roots.length === 0) {
    throw new Error("Packed context is missing input root metadata.");
  }

  return roots;
}

function getPackedInputRelativeRoot(
  packedProjectRoot: string,
  resolvedPath: string,
  type: InputType,
): string {
  const relativeResolvedPath = normalizePathForDisplay(
    path.relative(packedProjectRoot, resolvedPath),
  );

  if (type === "file") {
    return normalizePathForDisplay(path.dirname(relativeResolvedPath));
  }

  return relativeResolvedPath || ".";
}

function parseInputType(value: string): InputType {
  const normalized = value.trim();

  if (
    normalized === "file" ||
    normalized === "directory" ||
    normalized === "missing" ||
    normalized === "unsupported"
  ) {
    return normalized;
  }

  return "directory";
}

function parsePackedBlockHeaders(packedText: string): PackedBlockHeader[] {
  const headerPattern = new RegExp(
    String.raw`^${escapeRegExp(PACKED_BLOCK_SEPARATOR)}\nFILE: ([^\n]+)\nINPUT: ([^\n]*)\nSIZE: (\d+) bytes\n${escapeRegExp(PACKED_BLOCK_SEPARATOR)}\n`,
    "gm",
  );
  const headers: PackedBlockHeader[] = [];

  for (const match of packedText.matchAll(headerPattern)) {
    const filePath = match[1];
    const inputLabel = match[2] ?? "";
    const rawSizeBytes = match[3];

    if (!filePath || !rawSizeBytes) {
      continue;
    }

    headers.push({
      index: match.index,
      contentStart: match.index + match[0].length,
      filePath,
      inputLabel,
      sizeBytes: Number(rawSizeBytes),
    });
  }

  return headers;
}

function normalizeUnpackedContent(rawContent: string, expectedSizeBytes: number): string {
  let content = rawContent;

  while (
    content.length > 0 &&
    content.endsWith("\n") &&
    getUtf8ByteLength(content) > expectedSizeBytes
  ) {
    content = content.slice(0, -1);
  }

  return content;
}

function resolvePackedOutputPath(
  baseAbsPath: string,
  inputRoot: PackedInputRoot,
  packedPath: string,
): { relativeTargetPath: string; targetAbsPath: string } {
  const relativeFilePath = normalizePackedFilePath(inputRoot, packedPath);
  const normalizedRelativeInputRoot = inputRoot.relativeRoot === "." ? "" : inputRoot.relativeRoot;
  const relativeTargetPath = normalizePathForDisplay(
    path.posix.normalize(path.posix.join(normalizedRelativeInputRoot, relativeFilePath)),
  );

  if (
    relativeTargetPath === "." ||
    relativeTargetPath === ".." ||
    relativeTargetPath.startsWith("../")
  ) {
    throw new PackedPathError(`Packed target path escapes the output directory: ${packedPath}`);
  }

  const targetAbsPath = path.normalize(path.resolve(baseAbsPath, relativeTargetPath));

  if (!isSamePath(targetAbsPath, baseAbsPath) && !isPathInside(baseAbsPath, targetAbsPath)) {
    throw new PackedPathError(`Packed file path escapes the output directory: ${packedPath}`);
  }

  return { relativeTargetPath, targetAbsPath };
}

function normalizePackedFilePath(inputRoot: PackedInputRoot, packedPath: string): string {
  const normalizedPackedPath = packedPath.replaceAll("\\", "/");

  if (path.posix.isAbsolute(normalizedPackedPath) || path.win32.isAbsolute(normalizedPackedPath)) {
    throw new PackedPathError(`Packed file path must be relative: ${packedPath}`);
  }

  let relativeFilePath = path.posix.normalize(normalizedPackedPath);

  if (relativeFilePath === "." || relativeFilePath === ".." || relativeFilePath.startsWith("../")) {
    throw new PackedPathError(`Packed file path escapes the input root: ${packedPath}`);
  }

  const labelPrefix = `${inputRoot.label}/`;

  if (relativeFilePath.startsWith(labelPrefix)) {
    relativeFilePath = relativeFilePath.slice(labelPrefix.length);
  }

  if (inputRoot.type === "file" && !relativeFilePath.includes("/")) {
    relativeFilePath = normalizePathForDisplay(path.basename(inputRoot.resolvedPath));
  }

  if (relativeFilePath === "." || relativeFilePath === ".." || relativeFilePath.startsWith("../")) {
    throw new PackedPathError(`Packed file path escapes the input root: ${packedPath}`);
  }

  return relativeFilePath;
}
