export const DEFAULT_ESCAPE_EXTENSIONS: ReadonlySet<string> = new Set([
    ".md",
    ".mdc",
    ".mdx",
    ".json",
    ".jsonc",
    ".toml",
  ]);
  
  export const ESCAPED_MODULE_EXTENSIONS: ReadonlySet<string> = new Set([".ts", ".js"]);
  
  export const DEFAULT_IGNORED_DIRECTORY_NAMES: ReadonlySet<string> = new Set([
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "bower_components",
    "vendor",
    "dist",
    "build",
    "out",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".astro",
    ".turbo",
    ".vercel",
    ".output",
    ".cache",
    ".parcel-cache",
    "coverage",
    ".nyc_output",
    ".vitest",
    ".pytest_cache",
    "__pycache__",
    "tmp",
    "temp",
    "logs",
    "log",
  ]);